name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - main 
  repository_dispatch:
    types: [create-pull-request]

permissions:
  contents: write
  pull-requests: write
  
jobs:
  createPullRequest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x  

      - name: Install dependencies to generate docs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Sphinx Documentation
        run: |
          python generate_docs.py
      
      - name: Create auto-docs branch
        run: |
          git checkout main
          git pull origin main
          git branch -D auto-docs || true
          git checkout -b auto-docs
  
      - name: Add Generated Documentation
        run: |
          git add docs/build 
        
      - name: Commit Changes
        run: |
          git diff --quiet || git commit -m "Add sphinx documentation"

      - name: Push Branch
        run: |
          git pull origin main
          git push origin auto-docs

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add sphinx documentation
          body: >
            This PR is auto-generated by 
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
          title: 'Merge Sphinx Documentation'
          labels: automated pr
          branch: auto-documentation
          base: main
