name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - main 
  repository_dispatch:
    types: [create-pull-request]

permissions:
  contents: write
  pull-requests: write
  
jobs:
  createPullRequest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x  

      - name: Install dependencies to generate docs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Sphinx Documentation
        run: |
          python generate_docs.py
      
      - name: Create unique auto-documentation branch
        id: branch_name
        run: |
          BRANCH_NAME="auto-docs-$(date +%Y%m%d-%H%M%S)-$(git rev-parse --short HEAD)"
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          git checkout main
          git pull origin main
          git branch -D "${BRANCH_NAME}" || true
          git checkout -b "${BRANCH_NAME}"

      - name: Add Generated Documentation
        run: |
          git add docs/build 
      
      # git diff --quiet || git commit -m "Add sphinx documentation" owejnowenew
      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git rm -r --cached **/__pycache__|| true
          if ! git diff --quiet --exit-code -- ':!__pycache__'; then
            git commit -m "Add sphinx documentation"
          else
            echo "No relevant changes to commit."
          fi
          
      - name: Pull remote changes (if any)
        run: |
          git pull origin "${{ env.BRANCH_NAME }}" || echo "No changes to pull"

      - name: Push Branch
        run: |
          git push origin "${{ env.BRANCH_NAME }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add sphinx documentation
          body: >
            This PR is auto-generated by 
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
          title: 'Merge Sphinx Documentation'
          labels: automated pr
          branch: ${{ env.BRANCH_NAME }}
          base: main
